# Generated by Django 4.1.3 on 2022-11-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=15)),
                ('avg_max_temperature', models.IntegerField()),
                ('avg_min_temperature', models.IntegerField()),
                ('total_percipitation', models.IntegerField()),
                ('date', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, unique=True)),
                ('yield_val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=15)),
                ('max_temperature', models.IntegerField()),
                ('min_temperature', models.IntegerField()),
                ('percipitation', models.IntegerField()),
                ('date', models.CharField(max_length=8)),
            ],
            options={
                'unique_together': {('station_name', 'date')},
            },
        ),
    ]
