# Generated by Django 4.1.3 on 2022-11-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': 'weather'},
        ),
    ]
