# Generated by Django 4.1.3 on 2022-11-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_weather_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': 'Weather'},
        ),
    ]
